### ISSUE TITLE
Provide APIs for demography equality comparison

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1036]
This is needed upstream in stdpopsim. Currently uses internal API, which causes problems (see #1010). We should provide the basic functionality that stdpopsim needs here.

https://github.com/popsim-consortium/stdpopsim/issues/535

**Comment by jeromekelleher** [comment]
See also #1033, #1013 and other issues on the Demography API refactoring.

**Comment by jeromekelleher** [comment]
A pragmatic approach here might be to use the demography debugger to decide if two demography objects are equivalent in terms of their effects. So, we'd do something like
```python

def is_equivalent(self, other, eps_rel, eps_abs):
    try:
         self.assert_equivalent(other,  eps_rel, eps_abs)
         return True
    except AssertionError:
         return False

def assert_equivalent(self, other, eps_rel, eps_abs): 
      assert self.num_populations == other.num_populations
      for pop1, pop2 in zip(self.populations, other.populations):
           assert pop1.name == pop2.name
           # Some subtlety about how strict we should be here
      dbg1 = self.debug()
      dbg2 = other.debug()
      assert dbg1.num_epochs == dbg2.num_epochs
      for epoch1, epoch2 in zip(dbg1.epochs, dbg2.epochs):
          assert math.isclose(epoch1.start_time, epoch2.start_time, eps_rel, eps_abs)
          # Assert all the population parameters are the same, up to tolerance.
          assert numpy.allclose(epoch1.migration_matrix, epoch2.migration_matrix,  eps_rel, eps_abs)
          # Do something with the events that are not PopulationParameterChange and MigrationMatrixChange
          # Would need to be strict on these as the order in which MassMigrations etc happen is significant         
```

I'm probably forgetting stuff here, but you get the idea. We define equivalence in terms of the **effect** on the simulation state. There's still a bit of mopping up to do with the events that don't change the parameters, but in most cases it'll be straightforward PopulationSplit events that we compare.

The nice thing about this is that we become much less sensitive to the ordering of events within an epoch, so that stuff that doesn't matter can now be in any order.

The idea would then be to use this upstream in stdpopsim, so that we can get rid of the nasty event comparing code we have there.

@grahamgower, @apragsdale, any thoughts?

**Comment by grahamgower** [comment]
That does seem a lot simpler and more robust than what we do now. Maybe it's sufficient to compare the output of `DemographyDebugger.lineage_probabilities()` for the two models? I guess the downside there is it might not be as easy to report the differences back to the user.

**Comment by grahamgower** [comment]
One more thing that might be worth considering: we want to change some model implementations so that demographies like `((A,B),C)` actually have distinct population IDs for the common ancestor population of `(A,B)`, and the common ancestor population of AB and C. So it would be nice to compare these to the existing model imlementations which reuse one of the derived population's IDs for the ancestor ID. One thing we might do here, is to compare the `DemographyDebugger.coalescence_rate_trajectory()` for each of the leaf populations.

**Comment by petrelharp** [comment]
Comparing pop sizes and migration rates at all the epoch changes would be great, but not completely sufficient, because e.g. the order that MassMigrations happens can affect things. But as @grahamgower points out `lineage_probabilities` and coalescence rates would do it - maybe we'd need to do all three of these?

**Comment by jeromekelleher** [comment]
I think we can compare the MassMigrations directly per epoch after the other steps are done, and require exact equality among them. I don't want to rely on numerical methods here because (a) they're slow and (b) they've got more numerical fuzz.
