### ISSUE TITLE
Refactor RateMap to use numpy functions and add functionality

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1172]
The current [intervals.py](https://github.com/tskit-dev/msprime/blob/master/msprime/intervals.py#L29) is a minimal refactoring required to add a more sensible interface and deprecate the old RecombinationMap.  We should at least refactor the current code to use numpy APIs rather than (e.g.) Python bisect. Fleshing out some additional simple functionality would be good too (but optional).

@grahamgower, you've been involved in the recombination map code before - this is a clean slate now, any thoughts?

**Comment by grahamgower** [comment]
I don't expect it will be too hard to make the `slice` method work on numpy arrays using `numpy.searchsorted` for the binary search. What additional functionality did you have in mind?

**Comment by jeromekelleher** [comment]
> I don't expect it will be too hard to make the slice method work on numpy arrays using numpy.searchsorted for the binary search. 

Great! Was that you volunteering? :wink:

> What additional functionality did you have in mind?

I think the main thing would be better import - it would be nice if we could make ``read_hapmap`` a module function which returns a RateMap, and uses numpy functions to read the text file. I can't really think of anything else, I guess ``slice`` is the main thing we want.

Perhaps a version of slice where we say "give me the first x% of the map", which would be handy probably?

**Comment by hyanwong** [comment]
Two other things

1. I would really like something like `physical_to_genetic()` where a numpy array of physical positions is passed in and a set of genetic positions are returned. See my comment [here](https://github.com/tskit-dev/msprime/issues/902#issuecomment-609662481) and @daniel-goldstein 's below it.

2. We have previously made errors by applying a map for human chromosome 20 build 37 to a tree sequence based on build 38. We should be able to spot this sort of error because the sequence lengths are different in the different builds. Might it be sensible for the rate map to contain the sequence length as an attribute, to check for this sort of error? I don't know if this is provided by the hapmap rate maps? And should we also eventually aim for a RateMap to contain provenance metadata?

3. We have problems with recombination maps in which some of the rates are 0 (you do get this in some of the GRCh 38 maps). At the moment we are hacking round this by replacing any non-zero rates with epsilon, where epsilon is the smallest observed rate / 100. I guess we do want to allow rates of 0, so we'll continue to do this hack, but I mention it in case there are better solutions.

**Comment by jeromekelleher** [comment]
I think we want to have ``sequence_length`` as an attribute of the RateMap (it may already be). I think it's pretty simple now for someone to create a map masked out for zeros like you've done, if that's what they want, so we don't need to do anything special here. I don't think rate maps should contain provenance, for now at least.

**Comment by hyanwong** [comment]
Is the intention to save `self.cumulative` in the new RateMap, and use it for a simple numpy-based `physical_to_genetic` method, like we [did in the old one](https://github.com/tskit-dev/msprime/blob/afc3fc3d9c2605699dba48c1dd061282a3afa41f/msprime/intervals.py#L306). If so, I'd be happy to implement this (I need it for `tsinfer`)

**Comment by grahamgower** [comment]
Feel free to jump in here if you like @hyanwong---I certainly won't get to this until at least next week.

**Comment by hyanwong** [comment]
I just wanted to check if we wanted the same approach with the same method name (I don't see why not). If you aren't sure @grahamgower then perhaps @jeromekelleher could say? I was just going to reimplement enough for `physical_to_genetic`.

**Comment by grahamgower** [comment]
I have no idea about the physical_to_genetic stuff, sorry.

**Comment by hyanwong** [comment]
See https://github.com/tskit-dev/msprime/pull/1185 for this trivial addition. I didn't move `genetic_to_physical`, which seems a more complex function, so might need more debate?
