### ISSUE TITLE
Add `sequential_only` argument to `mutate( )`

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/msprime#1184]
Right now, we throw an error if a new mutation is above a kept mutation, although we have in the code [an option to not do this](https://github.com/tskit-dev/msprime/blob/master/tests/test_mutations.py#L1755). We throw an error because if the mutation process is not parent-independent (ie, if the distribution of derived state depends on the previous state), then there's no way to properly add interstitial mutations. However, this totally *does* make sense with parent-independent mutations. And, it's actually exactly what we need to do when adding neutral mutations to a SLiM simulation that had some selected mutations.

So, I think we want to add this argument, and I'm happy to do it once #1179 goes through. Questions:
- Is `sequential_only` an OK name for it?
- Do we want to check whether the mutation model is one of the parent-independent models, and throw a warning if not. I vote to not do this, and just make clear in the documentation that you should know what you're doing. The justification is that even if the model you're using is not parent-independent, everything is probably fine, because the proportion of sites with multiple mutations is very small anyhow.

So, use cases would be:

1. Adding more mutations to some part of an already-mutated tree sequence with Jukes-Cantor or InfiniteAlleles - maybe we recapitated, and want to add mutations to the newly-added ancestral stuff.

2. Adding mutations to a SLiM-produced tree sequence with selected mutations already on. I'm going to talk through this in more detail to make sure it makes sense. Suppose we did as follows:
```
ts0 = msprime.simulate(...)
sel_mm= msprime.SlimMutationModel(type=1)
ts1 = msprime.mutate(ts0, rate=0.01e-8, model=sel_mm, discrete=True)
# add selection coefficients, pass ts1 to SLiM for some more simulation, read it back in again
next_id = max([max(map(int, m.derived_state.split(","))) for m in ts1.mutations()])
neut_mm= msprime.SlimMutationModel(type=2, next_id=next_id)
ts2 = msprime.mutate(ts1, rate=0.99e-8, model=neut_mm, discrete=True, keep=True)
```
Just adding the neutral mutations in without regard to where there already were mutations is actually the right thing, if we imagine these two mutation types as independent Poisson processes. This is just what SLiM would do if we asked it to produce these two mutation types. Now suppose that we've got a site where ts1 has two mutations, one with id 5 and another with id 32 that happened on the background of the first. Following down a path from the root, we'd see alleles `""`, `"5"`, and `"5,32"`, since they "stack". Now suppose that in ts2 we added a new mutation with ID 123 in between these two. Now the alleles would be `""`, `"5"`, `"5,123"`, and `"5,32"`, because mutating the second time does not change the existing mutations at all. This is a bit surprising, as perhaps the last derived state should be `"5,123,32"`. The result is that any of the first (sel_mm, of type 1) mutations replace any of the second (neut_mm, type 2) mutations that might have appeared. This is a bit odd, and not something that one can do in SLiM, but also I think reasonable, because:
- genotypes, in terms of who has which selected alleles, are not changed by the new mutations
- computations of genetic diversity and so forth are just the same as you'd get under other ways of resolving this
- the new (type 2) mutations are neutral anyhow, so it shouldn't matter too much exactly who carries them.

If something else is desired, one could pretty easily go back through sites with multiple mutations and fix things up, so that the last allele in the example above is `"5,123,32"`. We could provide a method in pyslim to do this, even. (Doing SLiM-*nucleotide* mutations properly is a separate matter.)

Do you see any issues with this, @bhaller, @mufernando?

**Comment by bhaller** [comment]
> Is sequential_only an OK name for it?

Hmm.  Doesn't really communicate the idea to me, but then my head is not really in this space.  But I notice that you didn't use the word "sequential" once in your whole discussion above, so perhaps it is not really the key word for what's going on here.  I'm not sure what, in all this, is proposed to be "sequential".  A word that you *did* use, and that seems more descriptive to me, is "interstitial"; how about using that in the name?

> This is just what SLiM would do if we asked it to produce these two mutation types.

By default, in a non-nucleotide-based model, yes.

> The result is that any of the first (sel_mm, of type 1) mutations replace any of the second (neut_mm, type 2) mutations that might have appeared. This is a bit odd, and not something that one can do in SLiM...

You can do this easily, actually, but it's not the default.  See the `mutationStackGroup` and `mutationStackPolicy` properties of `MutationType`; if you set two mutation types to have the same "stacking group", and to have a stacking policy of `"l"`, then their mutations will replace each other.  But yes, it's not the default behavior, certainly, and it's probably rare for people to do it (unless, again, they're doing a nucleotide-based model, in which case this behavior would be automatic, since all nucleotide-based mutation types automatically share a single stacking group).

Those things said, this seems reasonable to me.  I kind of wonder whether it's worth the effort; as you say, "the proportion of sites with multiple mutations is very small anyhow", and "the new (type 2) mutations are neutral anyhow, so it shouldn't matter too much exactly who carries them".  Do we have a use case where somebody really cares about this?  But if it's straightforward to do, and if you don't think this will lead to confusion/errors on the part of users, then it sounds good to me!  :->

**Comment by jeromekelleher** [comment]
This has gone mostly over my head, but I'm with @bhaller on not being overblown by the ``sequential_only`` name. I don't have any better suggestions though.

**Comment by petrelharp** [comment]
>  I kind of wonder whether it's worth the effort; 

This is the least-effort way to allow people to add discrete-sites mutations to an already-mutated tree sequence, as is our standard SLiM/tree sequences workflow, so I think we definately want to do it!

**Comment by bhaller** [comment]
> > I kind of wonder whether it's worth the effort;
> 
> This is the least-effort way to allow people to add discrete-sites mutations to an already-mutated tree sequence, as is our standard SLiM/tree sequences workflow, so I think we definately want to do it!

Oh, I see – right now trying to do this would not just do a subtly-wrong thing, it would give an error and not work at all.  OK, yes, I see the necessity more clearly.

**Comment by petrelharp** [comment]
How about `allow_ancestral`, defaulting to `False`?

**Comment by bhaller** [comment]
`parent_independent`?

**Comment by petrelharp** [comment]
Hm, but one of our main use cases, SLiM mutations, aren't parent-independent..

**Comment by bhaller** [comment]
> Hm, but one of our main use cases, SLiM mutations, aren't parent-independent..

But isn't the mode that you are describing adding essentially designed to handle the case where they _are_ parent-independent – at least, by simply assuming that they *are* parent-independent, even if they really aren't?  I think I'm losing the thread of this a bit; but you wrote "However, this totally _does_ make sense with parent-independent mutations. And, it's actually exactly what we need to do when adding neutral mutations to a SLiM simulation that had some selected mutations."  And then when you wrote later on that "If something else is desired, one could pretty easily go back through sites with multiple mutations and fix things up", I thought that was talking about how you could fix up the mutational states to make them parent-dependent later, if that was actually what you wanted, because the algorithm being proposed here assumes that mutations are parent-independent.  Am I confused?

Sorry – I'm a visual thinker; I'm finding it difficult to think through all this without some kind of a diagram.

**Comment by petrelharp** [comment]
Parent-independent mutation is the only case where it's unambiguously fine. Other cases, like SLiM mutations, it's 'fine', with the caveats discussed above.

**Comment by bhaller** [comment]
> Parent-independent mutation is the only case where it's unambiguously fine. Other cases, like SLiM mutations, it's 'fine', with the caveats discussed above.

OK, right – exactly.  So what I'm saying is that the algorithm effectively assumes that mutations are parent-independent, and covers that case, and so that seems like a reasonable thing to call the flag – that is, semantically, precisely what the flag controls.  If people choose to use the flag in cases where mutations are _not_ parent-independent, they will have to think about the caveats you outlined, and passing "parent_independent=True" when they know that mutations are _not_ parent-independent will serve as a warning and a reminder to them that they need to think through the consequences of that choice, and perhaps do some after-the-fact fixup as you described.  That all seems good to me; the name "parent_independent" seems very descriptive.  Sorry if I'm missing the point here.

**Comment by jeromekelleher** [comment]
@petrelharp, is this still relevant now that we're going to allow silent mutations in tskit (and other recent updates on ``sim_mutations``)?

**Comment by petrelharp** [comment]
Yes, it still applies. And gee, I'd forgotten this was outstanding. I can have a go at this if you like.

**Comment by jeromekelleher** [comment]
> I can have a go at this if you like.

Yes please! (We want to get any of these big things sorted out, or at least have a forward compatible plan, as soon as we can so we can release)

**Comment by petrelharp** [comment]
And, I was just about to work on upgrading pyslim, for which I'll need this...

The name is outstanding. Above Ben said:

> That all seems good to me; the name "parent_independent" seems very descriptive. 

Good points, but I think the name should say more what it does. For instance, if we want to turn on this option even though the model is not parent independent, it would seem wrong to pass `parent_independent=True`. And, there's other implications of parent independentness.

I'll stick it in with `allow_ancestral` for now...

**Comment by petrelharp** [comment]
Hm, in C we ended up calling it `MSP_KEPT_MUTATIONS_BEFORE_END_TIME`.

**Comment by petrelharp** [comment]
Wait, this was already done, in #1209, and it's called [`add_ancestral`](https://github.com/tskit-dev/msprime/blob/9d0104ad63b963c793e063f807cee5964d3defb7/msprime/mutations.py#L1194).  🎉 🚀 

I'm going to close this, but please re-open if I'm wrong.

**Comment by jeromekelleher** [comment]
I was thinking that, but assumed there was more subtlety I hadn't appreciated!
