### ISSUE TITLE
Default behavior of samples and ploidy

### ISSUE THREAD

**Issue by apragsdale** [tskit-dev/msprime#1307]
In `sim_ancestry`, we now have the option to specify `ploidy`, which defaults to 2. So now the number of sampled sequences ends up being `samples * ploidy`. From an API design view, I find this a bit unnecessarily confusing, because the `samples` argument with default `ploidy=2` (or anything != 1) will not correspond to the number of samples given by `ts.num_samples`, and so the term "samples" is inconsistent across input and output.

It also ends up restricting possible sampling strategies in some analyses. This came up for me using the "dtwf" model, which is only possible to use with `ploidy=2` in `sim_ancestry` (which makes sense, it's a diploid Wright Fisher model). However, this means that I'm only allowed to sample an even number of sequences from each population. Using `msprime.simulate` from 0.7.4, I've recently run an analysis where I only sample a single sequence copy from each population in a multi-population model, which is a perfectly valid use of the "dtwf" model that wouldn't be possible in `sim_ancestry`.

I don't know how settled this API design choice is, but for both consistency with `ts.num_samples` and to not restrict previously possible sampling strategies, we might think about maintaining that `samples` refers to the number of sampled sequences instead of individuals. Thoughts?

**Comment by petrelharp** [comment]
Good point about the inconsistency. We *could* call it `individual_samples` or `num_individuals` or something instead? But, a big conceptual advantage of the new API is that it actually returns individuals (like, in the individual table); it's not clear quite what it should do if you asked for an odd number of chromosomes. For your use case, you could simulate individuals and drop one chromosome?

**Comment by grahamgower** [comment]
Maybe the param should be keyword only as well then?

**Comment by jeromekelleher** [comment]
I agree it's confusing for us as long-time users @apragsdale, but I think the decision we reached through various discussions is that getting ``n`` k-ploid individuals as the samples is what the vast majority of people will want. I agree that the collision with the concept of a sample node in tskit is unfortunate, so I'm open to any and all ideas for better names/making it a keyword only ARG. We do have to consider the complexities of drawing samples from different populations and at different times too, though, so ``num_individuals`` doesn't work.

The interaction with ``ploidy`` is a bit tricky. The parameter does two things: decide how many nodes we create per individual, and set the time-scale appropriately in the coalescent models. Since the DTWF is currently a very-much-diploid model, I thought it safer to raise an error if someone tries to set ploidy!=2. But, maybe this should just be a warning?

It's all quite confusing though, as I say, I'm very much open to ideas!

**Comment by jeromekelleher** [comment]
How about we add a ``samples_as_individuals=True`` boolean flag, which changes this behaviour? So by default we consider samples to be individuals, and make rows in the individual table and ``ploidy`` nodes for each one. But, if this is False, we revert to the old behaviour where we don't allocate individuals and we consider each sample to be a *node* and ploidy is just used to control things about the simulation model.

Or, would ``samples_as_nodes=False`` be clearer?

**Comment by hyanwong** [comment]
Just to jump in here, I've always been a bit uncomfortable about the term "samples" used in tskit - it's clear if you take a rigorous statistical hat on, but I'm not sure it's an intuitive term to a biologist, unless used as an adjective (e.g. "sample genome", or "sample individual"). It certainly confused me when I first started using tskit/msprime, and I try to avoid it when giving talks, as I think it could confuse non-programmers.

It may well be too late now,  with `ts.num_samples` being fixed in user's typing memory, and I may not be reflecting the general consensus, but I would vote for exploring other terms that could be applied to what we are now calling "sample nodes".

**Comment by grahamgower** [comment]
I think I would prefer "sample" used as a verb. E.g. have `ts.num_sampled` or `ts.num_sampled_nodes` as an alias for the (newly deprecated) `ts.num_samples`, then introduce `sample_individuals=True` or `sample_nodes=False` for the new keyword discussed above. But there's probably too much additional work changing other things, and little to be gained.

**Comment by jeromekelleher** [comment]
We're not going to change the meaning of ``samples`` from a tskit perspective before msprime 1.0 (I'm open to discussions about this on the tskit repo if people want to raise it there; but, it would be major upheaval for not a lot of gain, so I'm not terribly enthusiastic). 

There is the possibility of changing the terminology from the msprime side, though. Currently we have a keyword arg ``samples``, which accepts a list of ``Sample`` objects. Any suggestions?

**Comment by jeromekelleher** [comment]
This was resolved in #1360 - we now have a SampleSet object which allows you override the ploidy value.
