### ISSUE TITLE
Update DTWF model section

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1429]
The DTWF model docs need an update:

- The [examples section](https://tskit.dev/msprime/docs/latest/ancestry.html#discrete-time-wright-fisher) needs some examples to illustrate how its different from hudson (discrete time, really diploid, etc)
- Example section should link to the example we give for simulating multiple chromosomes
- The docstring should have a more formal description of what the model is. Can we be more precise here about population size, what time zero means, how we interpret start/end_time etc?#1428 

@apragsdale, @ivan-krukov  I think you're the closest to this model - would either of you be willing to pick this up?

**Comment by apragsdale** [comment]
I think there are still some outstanding issues dealing with start and end times in DTWF as well, bringing up #1304 again, where if we have an end time at generation t, the strict "<" semantics means we end up simulating t-1 generations instead of t, leading to discrepancies with the Hudson model.

I can try to get to the DTWF model docs, but it might not happen right away. I've got a lot of plates spinning at the moment and might not get to take this on until next week at the earliest.

**Comment by jeromekelleher** [comment]
Sounds good @apragsdale, thanks. I'll assign you for the moment, anyway.
