### ISSUE TITLE
Admixture event

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1479]
We added the population split and some other updates to the demgraphy API in #1478. However, we still need the MassMigration event to describe admixtures, which takes some getting used to. It would be much more intuitive if we had an ``Admixture`` event with the appropriate parameters.

Question is, what should those parameters be?

The discussion in #1013 provides some good background.

**Comment by grahamgower** [comment]
If a population split looks like `msprime.PopulationSplit(time=T_OOA, derived=["CEU", "CHB"], ancestral="OOA")`, then an admixture should probably look something like `msprime.Admixture(time=T_ADMIX, derived="ADMIX", ancestral=["AFR", "EUR", "ASIA"], proportions=[1/6, 2/6, 3/6])`.

Were you also thinking of having Branches and Mergers like @apragsdale has proposed for Demes? It seems reasonable to me to have a full complement of these "strict" demographic events at the low level.

**Comment by apragsdale** [comment]
Jerome, this would be up to you I think, but I don't know how much work you want to put into reimplementing all these specific events within msprime, since they can all be cast as mass migrations. With demes, I imagined that msprime would read through those different demographic events and convert them to the stripped down mass migrations that make those events happen. I guess I worry a bit about duplication and cost of maintenance, and think it might reduce future headaches to keep that high-level suite of demographic option just in the demes descriptions?

**Comment by jeromekelleher** [comment]
Yes, I think it comes down to whether we make demes the demography API for msprime 1.0 or not @apragsdale - see my comment on the Slack. Good to get your thoughts on that.
