### ISSUE TITLE
CLIs should support streams

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1520]
It would be nice to do stuff like
```
$ msp simulate 10 | msp mutate --rate=1 | msp_mutate --rate=2 --model=jc69 > final.trees
```

I suggest we change the semantics of the ``msp`` CLI as follows:

- If no files provided as arguments to ``msp simulate`` we write to stdout
- if no files are provided as arguments to ``msp mutate`` we read from stdin and write to stdout
- if one file is provided to ``msp mutate`` read from this file and write to stdout (although one could argue it should be the other way around, but then you are more likely to mistakenly nuke your file if you forget which way around it is) 

Tskit supports writing to streams, so it should be easy to implement.

@winni2k, any thoughts?

**Comment by winni2k** [comment]
I like it! Only issue I see is this: What happens if you forget to pipe the final result to a file? Do you get a bunch of binary gibberish printed to your screen? It would be great if we could avoid that.

I think the tool we could use as a model is `samtools view`. By default, samtools outputs to stdout in human-readable format (SAM records, but without header). If you want to write to a file, then you have to specify the output file with `-o out.sam`, which ends up having the headers required to make it machine readable. If you want to print machine readable data to stdout, then you have to supply an extra flag (e.g. `-h` to include SAM headers, or `-b` for BAM, or `-O SAM|BAM|CRAM`). 

If we adopted this model, then we could print a visual representation of the tree to stdout by default and require a flag like `-b` or `-O TS` to print binary data to stdout. If an output file is supplied as a second argument, then the binary format is assumed, but could be switched to the visual representation using another flag like `-t` or `-O TEXT`.

In practice I have two issues with this handling of stdout by samtools:

1.  It can be a bit annoying to have reams of SAM records printed to the screen by default, especially when working over a network terminal.
2. Sometimes I try to pipe the SAM records to another samtools call without specifying that the header should also be printed (`-h`) or that it should be in binary format (`-b`), resulting in an error because a malformed SAM file was piped to samtools.

However, I think both of these issues are minor and do not result in gross user error in practice. I also like that samtools gives me something nice to look at by default.

---

A separate question: Under this proposal, if you want to pipe a tree sequence to `msp mutate` and then write to a file you have to use stdout redirection (`>`). Is there any situation (perhaps on a cluster script or another pipeline) in which this might be a problem? I remember once having issues with `watch` and stdout redirection, although I eventually figured out that the workaround is to use single quotes around the command. Every bioinformatics tool I know has some sort of output file flag (i.e. `-o`), but most GNU tools manage to avoid such a file flag. Does this dichotomy simply reflect a general ignorance of stdout redirection in bioinformaticians, or is there a good reason for this?

**Comment by grahamgower** [comment]
It's also possible to test if stdout is a terminal. e.g.
```
$ python -c "import sys; print(sys.stdout.isatty(), file=sys.stderr)"
True
$ python -c "import sys; print(sys.stdout.isatty(), file=sys.stderr)" > /dev/null
False
```

**Comment by jeromekelleher** [comment]
Great points @winni2k!

I'm less concerned about the binary gibberish being output, as this opens up a can of worms for us in terms of writing out text representations and ultimately I think this would cause more confusion than just users realising they need to either redirect or use -O. I agree text output would be useful, but we'd need to do some work on the tskit side to make this fully lossless and robust, and it just doesn't seem worth it. 

In terms of visual output, the example above 
```
$ msp simulate 10 | msp mutate --rate=1 | msp_mutate --rate=2 --model=jc69 > final.trees
```
should work and be efficient by default. So, any human-readable output would get in the way of this.

FWIW, outputting the binary tskit data to stdout is the approach we've taken in stdpopsim, so there is precedent there.

There is *definitely* room for a better user experience at the shell with the ``tskit`` tools though, which is where I think it's better to focus. Things like ``tskit info simulation.trees`` should write out lots of useful stuff.

**Comment by jeromekelleher** [comment]
> It's also possible to test if stdout is a terminal. e.g.

I think this would perhaps be best handled in tskit, where we provide a "clever dump" that checks if the stream is a tty and writes text and otherwise binary. But, we'd need to have a full tree sequence text format, which we don't current have (we just have individual table formats, which aren't bullet proof).

So I would say, let's keep it simple here for now, but file an issue upstream in tskit to improve the console tools? I definitely agree it's good to have text output for the terminal, it's just we need to do some work to enable this properly.

**Comment by winni2k** [comment]
Otherwise, I like adding `-` later on if we later need to.

**Comment by jeromekelleher** [comment]
> This sounds really nice! How robust is this in practice? Does this require some environment variable to be set? Are we likely to get support requests from users for weird errors due to this?

It's a basic unix thing, so it should be pretty solid: https://man7.org/linux/man-pages/man3/isatty.3.html

**Comment by winni2k** [comment]
So I guess we could just print a warning message that no output will be printed if stdout is connected to a TTY?

**Comment by grahamgower** [comment]
> So I guess we could just print a warning message that no output will be printed if stdout is connected to a TTY?

Yeah, that's a sensisble approach. There should be some kind of `--force` flag to override this though, because occasionally someone will have weird requirements (or they're unfortunately stuck using a broken environment).

**Comment by jeromekelleher** [comment]
Let's not forget that we have to support Windows though. I'd prefer to keep it simple for the initial pass, and add on usability tweaks like this later.

**Comment by winni2k** [comment]
Ok, so the tty checking does not work if the terminal is behind a pipe:

```
python3 -c "import sys; print(sys.stdout.isatty(), file=sys.stderr)" | cat
False
ssh fuji 'python3 -c "import sys; print(sys.stdout.isatty(), file=sys.stderr)"'
False
python3 -c "import sys; print(sys.stdout.isatty(), file=sys.stderr)" | ssh fuji "cat"
False
```

So I don't think this will be a panacea, but practical in most cases.
