### ISSUE TITLE
Clarify multiple chromosomes section

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1565]
#1564 added an update to the [multiple chromosomes](https://tskit.dev/msprime/docs/latest/ancestry.html#multiple-chromosomes) section. There's a few outstanding questions for me:

1. How do we integrate the information about expected number of recombs? (see note)
2. When do we actually need to do this?

I think we need a clear message at the top saying "You don't need to do this unless you're explicitly modelling the relationship **between** individual chromosomes in a single simulation" (or whatever the right answer is). We're assuming a very high level of understanding at the moment, and I think people are going to google directly into this section and either be very confused, or do some very expensive simulations for no reason.

Could someone who understands this better than me have a pass through please? Preferably after reading through the rest of the [genome properties](https://tskit.dev/msprime/docs/latest/ancestry.html#genome-properties) section to get the right level.

@petrelharp, @JereKoskela or @apragsdale, any takers? (Or anyone else?)

**Comment by JereKoskela** [comment]
I'm probably not the best person for this seeing as I have no experience of the DTWF model, which I would expect to be the most common setting for multi-locus simulations. I'm happy to be involved and expand out the comment on multiple merger models though.

**Comment by apragsdale** [comment]
The docs are looking really nice now. As for this section, it's not clear to me what the note about expected number of recombination events would add to that section. If you wanted to include that, would it make more sense to place it in the Recombination section of Genome properties? Is there a specific point you want to make about how adding chromosome break points increases the map length?

For clarifying when you need to run multiple chromosomes, currently there is a line that reads: "The main purpose of simulating multiple chromosomes together (instead of running independent simulations for each chromosome) is to capture the correct correlation between trees on distinct chromosomes." This could be moved higher up in the section, maybe even put in an "Important" box, and with additional clarification that if you don't care about the correlation between fully unlinked loci that running independent simulations is more appropriate.

**Comment by jeromekelleher** [comment]
I'm not sure @apragsdale - this section got updated sequentially by a few people and it's lost it's narrative somewhere along the way. I'm hoping someone will pick it up and make it so that readers of all levels of experience will be able to get what they need from it. (I think what most people need is: you probably don't need to do this)
