### ISSUE TITLE
let numerical calculations with demography debugger use population names

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/msprime#1623]
As @jeromekelleher suggested in #1619 for `coalescence_rate_trajectories` and friends:

> Maybe we could should reuse the samples specification from sim_ancestry instead, so you can do things like {"A" : 2} rather than having to make an array of zeros?

**Comment by jeromekelleher** [comment]
I'm happy to pick this up @petrelharp. One question though: do I replace the current array-only syntax, or support it in addition to the standard ``samples`` syntax? I'd rather replace it if possible, as a future version of ``sim_ancestry`` will probably take an array of integers to define the sample individuals within a pedigree (which is why we don't currently support the array form).

**Comment by petrelharp** [comment]
I vote to go ahead and make it match sim_ancestry.

**Comment by jeromekelleher** [comment]
I'm working my way through this @petrelharp and it seems like the actual number of samples makes no difference it's just the *populations* we're interested in. So, we should specify a list of populations instead?

**Comment by jeromekelleher** [comment]
So, ``coalescence_rate_trajectory`` makes sense to take an arbitrary ``samples`` spec, but I'm not sure about ``mean_coalescence_time``. The spec says:

> Compute the mean time until coalescence between lineages of two samples drawn from the sample configuration specified in num_samples

I don't get the "two samples" bit - I'll open a PR with what I have and hopefully we can figure it out fairly quickly.
