### ISSUE TITLE
Should the msprime ARG representation have 2 recombination nodes or one?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/msprime#1942]
In https://github.com/tskit-dev/msprime/pull/665#issuecomment-458903503 @JereKoskela discussed the rationale for having each recombination event represented by 2 nodes in msprime. However, it seems like that argument is moot, as it should be possible to use a single node. This might be clearer (and tie in with the standard ARG visualisations, e.g. in the msprime paper, see below). We discussed this a bit on slack: some pertinent comments extracted below.

>>  [Yan] why do we create 2 separate nodes in [the case of recombination nodes). The docs say that of the 2 nodes “one identif(ies) the individual providing the genetic material to the left of the breakpoint and the other identif(ies) the individuals providing the genetic material to the right”...Wouldn’t it be possible (even preferable) to have one node (the individual in whom the nodes recombine), just like in fig 5?
>
>  [Jere] I don't think there is a reason as such. It is arbitrary whether you record the "child" node in which the lineages remain together, or the "parents" in which the material first splits up. Either way can be made to work by recording the right set of edges, and under the ARG, all three individuals live simultaneously. From a memory cost point of view, storing one individual would presumably be slightly better, and I think the only reason for two separate nodes is that it occurred to me first. I'm not sure whether it would break things to change now, how much work it would be, or whether it is worth doing.
> ... I'm not opposed to the single node approach. That's almost certainly what I'd do if I was setting this up from scratch.

This would, however, risk being a breaking change, possibly for no good reason, so it's worth discussing here.

**Comment by hyanwong** [comment]
Jere also says:

> To return briefly to the discussion about 1 vs 2 recombination nodes, do you have a view about a potential change @Jerome? As far as I can tell, the benefits of switching to one node are
An improved constant in the memory / parsing cost of output.
Easier visualisation (or other similar tasks) when the node table has been reordered.
A cleaner match with tskit if there were to be a "canonical" storage format with just one node. The canonical format could also be two nodes, though there seems little reason to go in that direction except compatibility with existing msprime code.
The downside is that this would break things if people are storing full ARGs and manipulating them in pipelines.

**Comment by hyanwong** [comment]
The msprime paper figure is like this:

![image](https://user-images.githubusercontent.com/4699014/145016302-31de022b-b766-4da7-8608-0afe68d555e6.png)

**Comment by jeromekelleher** [comment]
I think it's probably worth doing all right, even if just for our own use in working on the ARG paper. Here's my suggestion:

1. Add a NODE_IS_RECOMB (or something) flag to tskit (not sure if this is necessary, but it could be useful when we're trying to simplify ARG-like topologies. Not at all sure of this one, but see next point)
2. Set things up so that ``msprime.NODE_IS_RE_EVENT`` raises an error if used. This can tell people how to update their code to use the new one-node system. It's not perfect, as people might have been hard-coding values, but :shrug:
3. Change the msprime code to using one RE node. This should be a straightforward change, I'd imagine @JereKoskela?

Regarding the new flag, as we go forward and try to make more ARG functionality, it may be worth chaning the behaviour of simplify to keep RECOMB nodes by default. However, this doesn't help with the interesting simplify operation that we might genuinely want to do - given a "full" ARG output by a simulation, reduce it down to the "observable" ARG, which has the (or "a" I guess, things get tricky when there's multiple recombinations at a given point) recombination node corresponding to every tree breakpoint.

**Comment by jeromekelleher** [comment]
Tagging this for 1.1 for the moment, but we may want to let it go until 1.2 so we don't hold up the pedigree stuff.

**Comment by JereKoskela** [comment]
It should be fairly straightforward. I'd have to re-derive some likelihood functions and tweak some corresponding tests, but that should be doable. I have no capacity for working on this until at least mid-January though. Are there target release dates for 1.1 or 1.2 yet?

**Comment by hyanwong** [comment]
> 1. Add a NODE_IS_RECOMB (or something) flag to tskit (not sure if this is necessary, but it could be useful when we're trying to simplify ARG-like topologies. Not at all sure of this one, but see next point)

If we do decide to do this, is it even worth adding a `tskit.NODE_IS_RECOMB` constant soon (but undocumented and unused), so that it's easy to start coding it in msprime without having to release another tskit version? Or do we simply define it in `msprime` first, and move it over to tskit afterwards?

**Comment by jeromekelleher** [comment]
> I have no capacity for working on this until at least mid-January though. Are there target release dates for 1.1 or 1.2 yet?

We want to get 1.1 out ASAP really, so let's push it down for 1.2 then. There's no major hurry.

**Comment by jeromekelleher** [comment]
> If we do decide to do this, is it even worth adding a tskit.NODE_IS_RECOMB constant soon (but undocumented and unused), so that it's easy to start coding it in msprime without having to release another tskit version

I think we can just define it in msprime first, and then when we're sure it's the right approach move it to tskit. We can pop out a point release of tskit before msprime 1.2 and depend on that.

**Comment by hyanwong** [comment]
As part of this it would be helpful to be able to convert an msprime tree sequence with ARG nodes to the new 1-node format. I think this should do it. I don't think we are using bit 2 for anything in the tskit node flags, so it's the next one available after tskit.NODE_IS_SAMPLE. I don't know if we want to also define a tskit version of `NODE_IS_CA_EVENT` in this lower area, but I'm not sure if that's actually a redundant flag anyway. I mean, isn't it calculable from the arrangement of edges?

```
msprime.NODE_IS_RECOMB = 2  # Use the "reserved" space in the bitfield for the new node type, as we'll eventually port this to tskit

def convert_to_single_rec_node(ts):
    tables = ts.dump_tables()
    tables.nodes.clear()
    node_mapping = np.zeros(ts.num_nodes, dtype=tables.edges.child.dtype)
    node_id = 0
    while node_id < ts.num_nodes:
        node_mapping[node_id] = tables.nodes.num_rows
        node = ts.node(node_id)
        if (node.flags & msprime.NODE_IS_RE_EVENT):
            node_id += 1
            assert node_id < ts.num_nodes
            assert ts.node(node_id).flags & msprime.NODE_IS_RE_EVENT
            assert ts.node(node_id).time == node.time
            node_mapping[node_id] = tables.nodes.num_rows
            node.flags &= ~msprime.NODE_IS_RE_EVENT  # Unset the NODE_IS_RE_EVENT bit
            node.flags |= msprime.NODE_IS_RECOMB
        tables.nodes.append(node)
        node_id += 1
    tables.edges.parent = node_mapping[tables.edges.parent]
    tables.edges.child = node_mapping[tables.edges.child]
    tables.mutations.node = node_mapping[tables.mutations.node]
    tables.sort()
    return tables.tree_sequence()
```

The logic is that we clear the node table and loop over the nodes, adding then data back in. However, when we meet a pair of recombination nodes, we only add a single one, and keep a mapping of the old to the new nodes IDs, which we then use to update the nodes IDs in other tables. I think that's enough to preserve all the information, right @JereKoskela ? The number of edges stays the same, and for a diamond event we just get 2 separate edges adjacent on the genome, with the same parent and child (so the diamond can be erased by `squash_edges`).

**Comment by JereKoskela** [comment]
Quoting myself from #1978 for the record:

> Trying to get the likelihood tests to pass has reminded me of what exactly the issue was with single-node recombination storing.

>Suppose you have a lineage with a segment of trapped non-ancestral material, and that it forms a diamond. It will be impossible to recover the breakpoint from the nodes and edges, and therefore impossible to determine whether or not the trapped segment should be regarded as "extant" links for the purpose of working out a rate of effective recombinations in the likelihood calculation.

>Fortunately, #1979 is exactly what we need to fix this, but it means the metadata update and fixing the likelihood need to be done concurrently.

**Comment by jeromekelleher** [comment]
> Suppose you have a lineage with a segment of trapped non-ancestral material, and that it forms a diamond. It will be impossible to recover the breakpoint from the nodes and edges, and therefore impossible to determine whether or not the trapped segment should be regarded as "extant" links for the purpose of working out a rate of effective recombinations in the likelihood calculation.

I can see that we'd have a problem when we get a breakpoint in ancestral material and we have a diamond, but not *non* ancestral. In the simplest case, suppose we have a segment (0, L, a) which is split at position x; we then have two segments (0, x, b) and (x, L, b) (where b is the recombination node). Now, if they coalescence again immediately into c we'll record two edges, (0, x, c, b), and (x, L, c, b), but since these are squashable, msprime will record this as (0, L, c, b). 

So is the answer to try and spot these cases and disable squashing temporarily? A quick hack to try it out would be to disable squashing temporarily in the flush_edges function.

But, this is a different issue to what you're talking about here I think @JereKoskela - can you sketch out an example to make it clearer please? (I think it's worth working through this stuff, it'll be useful for the paper anyway, since you can't easily evaluate the likelyhood on a plain node breakpoint annotated ARG either)

**Comment by JereKoskela** [comment]
That's exactly the situation I had in mind @jeromekelleher. Here is a a slightly more involved example which illustrates the problem with nonancestral breakpoints too, and also shows why disabling edge flushing isn't enough by itself:

The rate for the next event is (n choose 2) + r k, where r is the recombination rate, n is the number of extant lineages, and k is the number of extant links which lie between ancestral material (henceforth abbreviated to just extant links). The issue at hand is working out k for the interval of time between a recombination node, and the subsequent coalescence node which turns it into a diamond. I'll assume for simplicity that they're two successive events, but the same thing happens even when they're not.

Suppose node A is the child of a recombination node B, and that A carries three segments: (0, w), (x, y), (z, L), with w < x and y < z, so that there are two nonancestral gaps. We get three edges from A to B, one per segment. Now suppose C is the common ancestor node that completes an A-B-C diamond. There will also be three edges from B to C, one per segment.

If the break point at B was in ancestral material, then disabling edge flushing would let us pin down the breakpoint and hence reconstruct how many extant links there are between B and C. However, if the break point is in nonancestral material, then exactly one of the gaps (w, x) and (y, z) will be extant (the one which does not contain the breakpoint), but there will be no way to know which one. It also won't be enough to disable edge flushing, because the gaps mean they wouldn't get flushed anyway.

**Comment by jeromekelleher** [comment]
Hmmm, right.

So should we go ahead with adding the breakpoint metadata first and then fix the likelihood calculations after? I think it's OK if it's broken in the repo for a little bit.

**Comment by JereKoskela** [comment]
> So should we go ahead with adding the breakpoint metadata first and then fix the likelihood calculations after? I think it's OK if it's broken in the repo for a little bit.

That sounds like a good plan to me. I'll PR my changes thus far so you can have a look. I should be able to fix the likelihoods pretty quickly once the metadata is in place, so the repo shouldn't stay broken for long. 

> (Side note, and totally unoriginal insight: this really is a terrible model for inference, isn't it? All sorts of totally unknowable things are required to compute a likelihood.)

True, though that's not all that unusual in missing data problems. Even with something pretty simple like IID samples from a mixture of Gaussian densities, one of the most efficient approaches to inference is to assume you know which mixture component generates each sample, and integrate out the allocation afterwards.

**Comment by hyanwong** [comment]
> > Suppose you have a lineage with a segment of trapped non-ancestral material, and that it forms a diamond. It will be impossible to recover the breakpoint from the nodes and edges, and therefore impossible to determine whether or not the trapped segment should be regarded as "extant" links for the purpose of working out a rate of effective recombinations in the likelihood calculation.

I can see that by storing the edges (rather than breakpoints on nodes) we lose the position of breakpoints on recombination nodes where recombination is not in the ancestral material (i.e. in a so-called "trapped" segment), but I can't see how storing the recombination as two nodes helps with this. Surely the position of the breakpoint is lost in this case too? I'd like to understand this properly, as I think it is relevant to the node vs edge annotation discussion.

**Comment by JereKoskela** [comment]
> I can't see how storing the recombination as two nodes helps with this. Surely the position of the breakpoint is lost in this case too?

The exact position of the breakpoint is lost, but you retain information about which non-ancestral gap contains the breakpoint, even when there are several gaps. That's enough to work out how many links are available for an effective recombination, and hence the rate of effective recombinations, in the next time interval.

**Comment by jeromekelleher** [comment]
Ahh.

**Comment by hyanwong** [comment]
> > I can see how that might work, but I can't see on earth how you would generalise this to multiple breakpoints.
> 
> I think the only way would be to have `n + 1` nodes for `n` breakpoints, so that you can sandwich each break in between two nodes.

Right, but then each node is no longer an ancestral genome: some genomes would be represented by multiple nodes, which would break the tskit data model (I think)

**Comment by JereKoskela** [comment]
> Right, but then each node is no longer an ancestral genome: some genomes would be represented by multiple nodes, which would break the tskit data model (I think)

Yes, you're right. I think it might be possible to make things work by just following the pattern of switches between two nodes: one jump from node A to B or vice versa to localise each breakpoint. But the metadata way seems at least as clean.

**Comment by hyanwong** [comment]
I think this argues that the metadata way is the right one. The scheme that was previously devised (2 RE nodes) seems a specific nod to the likelihood calculations on a Griffiths ARG (the one with a single breakpoint), rather than a method for encoding a general 'Recombination Graph" with any pattern of inheritance from the 2 parent genomes (e.g. gene conversion).

**Comment by jeromekelleher** [comment]
I think we've settled on the existing two-node representation (or at least, any minor advantages to having one node are much outweighed by the trouble of changing this).
