### ISSUE TITLE
Assuming existence of ``properties`` and ``additionaProperties`` in population metadata schema

### ISSUE THREAD

**Issue by grahamgower** [tskit-dev/msprime#1947]
I *think* the problem is on the msprime side, not the SLiM side.

SLiM script (only works in bleeding edge git version of SLiM)
```R
initialize() {
	initializeMutationRate(1e-7);
	initializeMutationType("m1", 0.5, "f", 0.0);
	initializeGenomicElementType("g1", m1, 1.0);
	initializeGenomicElement(g1, 0, 99999);
	initializeRecombinationRate(1e-8);
	initializeTreeSeq();
}

1 {
	sim.addSubpop("p0", 500);
	p0.name = "awesomepop";
}

2000 late() { sim.treeSeqOutput("/tmp/slim-p0.ts"); }
```
[Output file](https://github.com/tskit-dev/msprime/files/7691200/slim-p0.pptx) -- rename to `slim-p0.ts`.

Recapitation script:
```python
# recap.py
import tskit
import msprime

print("tskit", tskit.__version__)
print("msprime", msprime.__version__)

demography = msprime.Demography()
demography.add_population(name="awesomepop", initial_size=500)

ts = tskit.load("slim-p0.ts")
ts = msprime.sim_ancestry(
    initial_state=ts, demography=demography, recombination_rate=1e-8
)
ts.dump("slim-recapitated.ts")
```

```
$ python recap.py
tskit 0.4.0b1
msprime 1.0.4
Traceback (most recent call last):
  File "/tmp/recap.py", line 11, in <module>
    ts = msprime.sim_ancestry(
  File "/home/grg/.local/lib/python3.9/site-packages/msprime/ancestry.py", line 1181,
in sim_ancestry
    sim = _parse_sim_ancestry(
  File "/home/grg/.local/lib/python3.9/site-packages/msprime/ancestry.py", line 977, in _parse_sim_ancestry
    demography.insert_extra_populations(initial_state)
  File "/home/grg/.local/lib/python3.9/site-packages/msprime/demography.py", line 1136, in insert_extra_populations
    additional_properties = schema["additionalProperties"]
KeyError: 'additionalProperties'
```

ping @bhaller @petrelharp

**Comment by grahamgower** [comment]
I think this msprime code is wrong, because the [tskit metaschema](https://tskit.dev/tskit/docs/latest/metadata.html#full-metaschema) doesn't mandate the presence of the "properties" field nor "additionalProperties" (only "codec" is required). I'm not entirely sure the "name" or "description" fields need to be listed in the properties anyhow.
https://github.com/tskit-dev/msprime/blob/c034a5d24a39ad888a603a2c2042298ad0f8265f/msprime/demography.py#L1133-L1154

FYI, here is the schema for the SLiM population table metadata.
```
print(json.dumps(ts.tables.populations.metadata_schema.schema, indent=2))
```
```json
{
  "$schema": "http://json-schema.org/schema#",
  "codec": "json",
  "description": "SLiM schema for population metadata.",
  "examples": [
    {
      "bounds_x0": 0.0,
      "bounds_x1": 100.0,
      "bounds_y0": 0.0,
      "bounds_y1": 100.0,
      "female_cloning_fraction": 0.25,
      "male_cloning_fraction": 0.0,
      "migration_records": [
        {
          "migration_rate": 0.9,
          "source_subpop": 1
        },
        {
          "migration_rate": 0.1,
          "source_subpop": 2
        }
      ],
      "selfing_fraction": 0.5,
      "sex_ratio": 0.5,
      "slim_id": 2,
      "name": "p2"
    }
  ],
  "properties": {
    "bounds_x0": {
      "description": "The minimum x-coordinate in this subpopulation.",
      "type": "number"
    },
    "bounds_x1": {
      "description": "The maximum x-coordinate in this subpopulation.",
      "type": "number"
    },
    "bounds_y0": {
      "description": "The minimum y-coordinate in this subpopulation.",
      "type": "number"
    },
    "bounds_y1": {
      "description": "The maximum y-coordinate in this subpopulation.",
      "type": "number"
    },
    "bounds_z0": {
      "description": "The minimum z-coordinate in this subpopulation.",
      "type": "number"
    },
    "bounds_z1": {
      "description": "The maximum z-coordinate in this subpopulation.",
      "type": "number"
    },
    "description": {
      "description": "A description of this subpopulation.",
      "type": "string"
    }
  },
  "female_cloning_fraction": {
    "description": "The frequency with which females in this subpopulation reproduce clonally (for WF models).",
    "type": "number"
  },
  "male_cloning_fraction": {
    "description": "The frequency with which males in this subpopulation reproduce clonally (for WF models).",
    "type": "number"
  },
  "migration_records": {
    "items": {
      "properties": {
        "migration_rate": {
          "description": "The fraction of children in this subpopulation that are composed of 'migrants' from the source subpopulation (in WF models).",
          "type": "number"
        },
        "source_subpop": {
          "description": "The ID of the subpopulation migrants come from (in WF models).",
          "type": "integer"
        }
      },
      "required": [
        "source_subpop",
        "migration_rate"
      ],
      "type": "object"
    },
    "type": "array"
  },
  "name": {
    "description": "A human-readable name for this subpopulation.",
    "type": "string"
  },
  "selfing_fraction": {
    "description": "The frequency with which individuals in this subpopulation self (for WF models).",
    "type": "number"
  },
  "sex_ratio": {
    "description": "This subpopulation's sex ratio (for WF models).",
    "type": "number"
  },
  "slim_id": {
    "description": "The ID of this population in SLiM. Note that this is called a 'subpopulation' in SLiM.",
    "type": "integer"
  },
  "required": [
    "slim_id"
  ],
  "type": [
    "object",
    "null"
  ]
}
```

**Comment by jeromekelleher** [comment]
Thanks for the detailed report @grahamgower, this is very helpful.

There is a bug here in msprime in that we're assuming that these keys exist in the schema dictionary. (Which is highlighting the need for a higher level API here!)

I think we just need to be more careful about accessing the schema dictionary keys for now.

**Comment by grahamgower** [comment]
I think there's a bug in the SLiM schema here too (the `female_cloning_fraction` etc. fields should be nested within the "properties" section). Ping @bhaller

**Comment by grahamgower** [comment]
> How soon do folks want to see a fix for this released?

I guess its important to have the recapitation workflow fixed before SLiM 3.7 is released. (I think this is broken regardless of whether someone manually sets the "name" property of a SLiM subpopulation). Unfortunately, I don't have the bandwidth to work on this until next year.

**Comment by jeromekelleher** [comment]
I can fix the basic bug here on the msprime side in a few minutes, the question is whether to push out a point release as well. 

@bhaller, good to get your thoughts here.

**Comment by grahamgower** [comment]
> I can fix the basic bug here on the msprime side in a few minutes, the question is whether to push out a point release as well.

Right. There are a lot of moving parts here (potential SLiM fixes needed) which should probably be tested against your msprime fix before bothering with a msprime point release.

**Comment by jeromekelleher** [comment]
Thanks for reporting back from the bleeding edge!

**Comment by benjeffery** [comment]
Really need to get round to the higher-level metadata APIs in tskit. Seeing these issues certainly ups the priority!

**Comment by bhaller** [comment]
This is the first I recall hearing of this distinction between `properties` and `additionalProperties`; what is the semantic distinction being drawn there?  I looked at https://tskit.dev/tskit/docs/latest/metadata.html#full-metaschema again, but I don't see an explanation there; is this a distinction that is internal to msprime, or did I miss it in the doc?  Anyhow, I don't think I have enough context on all this to have an opinion.  :->  I think the question of whether an msprime point release is needed is up to @grahamgower, unless any of @petrelharp's SLiM tests will require a point release in order to execute correctly (which may well be true).

@grahamgower, I see the PR you posted at https://github.com/MesserLab/SLiM/pull/255, thanks; that does look like a simple typo that snuck in somewhere.  I will commit the fix from my side since I want to do some other stuff related to this change.  I'll post again when I've done that, which will be very soon today, I think.

**Comment by jeromekelleher** [comment]
> I found the discussion of additionalProperties in the metadata doc; I was confused since it is only discussed under the struct case, but I guess it is also a thing in the JSON case? Why would someone set it to false in the JSON case, I wonder?

It's a general [json schema thing](http://json-schema.org/understanding-json-schema/reference/object.html#additional-properties)

Someone might want to set it to ``false`` to say "you can't add any stuff other than the things defined here". Whether that's a good idea is another question.

I think it defaults to "true", and msprime has a bug here because it assumes it's explicitly set. It's an easy fix.

@grahamgower, you've got the best overview here: I'll make a fix for this in the next day or two, just let me know whether we should also pop out a release as well.

**Comment by bhaller** [comment]
OK.  I've just committed a fix to SLiM's population table metadata schema, following @grahamgower's lead (thanks!).  I also added `additionalProperties` to that schema, with `true` since it is a JSON schema.  If I understand all this correctly, that will mean that msprime's bug (failing if `additionalProperties` is missing) will no longer be triggered, so while it does seem that there is a bug there, I think interoperability ought to work now that SLiM is putting the key in.  @grahamgower, can you confirm that your pipeline now works?  If so, then I think no msprime point release will be needed.  The metadata schema without `additionalProperties` was not in any SLiM release; that (and the other bug with the schema) happened in the conversion of the schema from `struct` to `JSON` for SLiM 3.7.  I've added some debugging code in SLiM to try to ensure that such problems do not recur.  Note that I did *not* add `additionalProperties` to SLiM's top-level metadata schema, since it has never been there before, and that has never caused any problems.

So, hopefully I haven't screwed this up; my understanding of all this metadata stuff is still evolving.  :->  Let me know if anything further is needed from my side.

**Comment by petrelharp** [comment]
Thanks all! What @bhaller says sounds right to me.

**Comment by jeromekelleher** [comment]
OK, putting in the 1.1.0 milestone for now so, but happy to pop out a point release if that'll help.
