### ISSUE TITLE
Disable dependabot

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1972]
Looks like dependabot is still working here @benjeffery (and opening up loads of branches on forks) - how do we go about turning it off?

**Comment by grahamgower** [comment]
Unfortunately, I think this is something each user needs to toggle in their own fork (discussion here: https://github.com/dependabot/dependabot-core/issues/2804). See the "actions" section under the "settings" tab.

![fork-actions](https://user-images.githubusercontent.com/8665077/148406776-d33f5a2e-808e-4385-809f-b58c5523ca42.png)

**Comment by benjeffery** [comment]
I'll remove it as we did on tskit - then it will stop firing on forks.

**Comment by grahamgower** [comment]
"We're aware of this issue and planning a fix. The workaround for now is to delete the fork and re-create it without enabling Dependabot security updates. Dependabot version updates (setup from config file) isn't enabled by default on new forks but will be if security updates has ever been turned on and since disabled."

**Comment by benjeffery** [comment]
I think that is only for security updates, so removing the config we have should still stop most of it.

**Comment by grahamgower** [comment]
An alternative way of keeping up to date is to use a actions/cron job. Here's what the `hypothesis` team use: https://github.com/HypothesisWorks/hypothesis/blob/master/.github/workflows/update-deps.yml

**Comment by benjeffery** [comment]
Interesting, thanks @grahamgower
