### ISSUE TITLE
Use a new name for ``record_full_arg``?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1987]
We are changing the form of the output in the ``record_full_arg`` option, and while doing things like making the constants raise an error will help (#1985 ) it's still possible (likely, even) that we'll break people's code silently, since they are quite likely to just hard code the flags values.

One way we could avoid this would be to make a new option for ``record_full_arg``, and raise an error if the ``record_full_arg`` option is used.

How about ``record_arg``? The ``full`` is probably unhelpful anyway?

@hyanwong @JereKoskela - thoughts on terminology here?

**Comment by hyanwong** [comment]
I find "record" a little confusing, as I would expect that to produce the same topology but with extra recorded nodes. I know this is sometimes a source of confusion, because the topology can be completely different, as it's essentially using a different set of random numbers for the breakpoints, coalescences, etc. Perhaps something like "output_arg", "create_arg", or "generate_arg" would be better? I've got used to "full", so I can't quite make up my mind, but I guess we aren't saving the breakpoints in non-ancestral chunks (unless those are in metadata?), so perhaps "full" is less complete than a Griffiths ARG affectionate would hope anyway?

**Comment by jeromekelleher** [comment]
The "record" bit came trying to follow the pattern set for ``record_migrations``. This may not be the most heavily used feature, so perhaps not that important to be consistent.

**Comment by JereKoskela** [comment]
I agree that "full" can carry misleading connotations about the big ARG, so would probably be best dropped. I'm indifferent about "record" vs "create" vs "output" vs "generate" etc. I think they all have the potential for the same confusion about being different random draws than a tree sequence produced using the same random seed. My inclination would be to maintain consistency with `record_migrations`, but I'm happy to go with something else too.

I'll make the change to whatever is the consensus name when I get around to fixing the likelihood functions.

**Comment by jeromekelleher** [comment]
Just ``record_arg`` then? It's no less confusing than alternatives, and at least there's a reason for using it.

**Comment by jeromekelleher** [comment]
OK, done.

Leave this one with me @JereKoskela, I'll need to  think a bit about the compatibility and how we manage the flags at the same time.

**Comment by jeromekelleher** [comment]
Given we're not changing any of the code now, I don't think there's any motivation in changing the name.
