### ISSUE TITLE
Adding option to progress bar when running simulation and writing outputs

### ISSUE THREAD

**Issue by shaharMazia** [tskit-dev/msprime#2020]
Hi all,
First thing, I am a new user of this repo, and in general not very familiar with the open source principles (I know the idea but never contribute to any repo).

I am running a relative simple simulation, and save a VCF file later  (example code is provided below).

I noticed it may take a few minutes, or even more if I raise the numbers a bit, and it would be nice to have a progress bar (maybe using tqdm) while both the simulation is running, and while saving the VCF. I believe it shouldn't be hard to add. I am not familiar enough with the code, and don't know the procedure of contributing to an open source. 
What do you guys think? 

Example for my simulation:
```
pop_configs = [msprime.PopulationConfiguration(sample_size=500), msprime.PopulationConfiguration(sample_size=500)]

ts = msprime.simulate(population_configurations=pop_configs, length=5e8, Ne=2000, mutation_rate=5e-7,
                                     recombination_rate=1e-8, demographic_events=[msprime.MassMigration(10000, source=1, dest=0, 
                                     proportion=1)])
ts.write_vcf(f)

```

**Comment by benjeffery** [comment]
Hi @shaharMazia!
Thanks for your suggestion. Adding a progress bar to msprime simulations is not easy, as the time and number of operations isn't easily predictable from the initial parameters. I'm sure with some research we might be able to make some guess about the runtime, but it would be quite some work. Also the actual simulation is performed in C code that doesn't report to python till it finishes.

Thanks for showing an interest in open source!

**Comment by jeromekelleher** [comment]
As @benjeffery says @shaharMazia, it's actually quite hard to predict how long a simulation is going to take (or even to figure out how far through a give one you currently are). See the Recombination section (and "time complexity of hudson's algorithm") section in the [msprime 1.0 paper](https://academic.oup.com/genetics/article/220/3/iyab229/6460344) for more info.

Since this is something we really don't know how to do, I'm going to close this issue. Please feel free to discuss further though, and thanks participating!
