### ISSUE TITLE
msprime census docs

### ISSUE THREAD

**Issue by molpopgen** [tskit-dev/msprime#2065]
Paraphrasing from tskit-slack.

The census docs state:
```
This can be useful when you wish to study haplotypes that are ancestral to your simulated sample, or when you wish to know which lineages were present in which populations at specified times.
```

However, census nodes are *not* sample nodes, making it currently impossible to study such haplotypes via the statistics framework.  Related: I cannot find docs stating that these nodes do not have `NODE_IS_SAMPLE` set.

To "study ancient haplotypes", shouldn't one prefer `SampleSet`?  The main difference is that census nodes are in the direct ancestry of samples at time 0, but it isn't really clear what one can do with that info?

**Comment by molpopgen** [comment]
PS, I'll be gone for the next several days...

**Comment by petrelharp** [comment]
Hm, let's see. A census event is useful because it tells you the locations (well, populations) of the lineages at the time, and what segments the ancestry were broken up into. In other words, it tells us what the haplotypes were then, and where they were. The nodes shouldn't be samples because we don't know their whole genomes (which precludes us using the statistics also). This is different information than having sample sets at the time.

**Comment by jeromekelleher** [comment]
Aha, yes, I forgot about the non-ancestral bits of the census nodes. They'd be missing data if marked as samples.

**Comment by molpopgen** [comment]
I think the issue, as I said, are with the docs--what is "analysis" when the primary documented analysis framework is not available?

**Comment by petrelharp** [comment]
This would be analyses that look at the trees. For instance, one that look at which segments of genome are inherited from which location at the census time. Let's see, the docs say that:

> This can be useful when you wish to study haplotypes that are ancestral to your simulated sample, or when you wish to know which lineages were present in which populations at specified times.

I think it's accurate - do you have any suggestions of how to improve this?
