### ISSUE TITLE
flake8 line length recs from Black have changed-- update this?

### ISSUE THREAD

**Issue by andrewkern** [tskit-dev/msprime#2092]
https://github.com/tskit-dev/msprime/blob/4e5672ad3d569da6b79f4ab017399324bca0d70d/.flake8#L4

I was poking around figuring out how to set up auto-linting on a new project and was comparing what `msprime` was doing vs the internet. It looks like Black now recommends slightly different settings, including a line length of 88 😱 

Here is the current link to the Black style guide on line length. The link in the `.flake8` file is now out of date

https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#line-length

not sure if anyone wants to change this but there it is

**Comment by jeromekelleher** [comment]
I'm happy to change this, 90-ish is my line-length of choice as well.

@benjeffery, any thoughts?

**Comment by andrewkern** [comment]
i'd be happy to submit this PR @jeromekelleher-- trying to learn more about this infrastructure stuff

**Comment by jeromekelleher** [comment]
Let's see what Ben thinks, he's more on top of this stuff. He'll be back in a few days.

**Comment by benjeffery** [comment]
We don't configure black at all (that's the whole idea behind black) so changing that config to 88 won't reformat any code. Flake8 as we have configured is already allowing lines up to 88 long (e.g. `tests/test_ancestry.py:57`) as we are using B950:

`B950: Line too long. This is a pragmatic equivalent of pycodestyle’s E501: it considers “max-line-length” but only triggers when the value has been exceeded by more than 10%. You will no longer be forced to reformat code due to the closing parenthesis being one character too far to satisfy the linter. At the same time, if you do significantly violate the line length, you will receive a message that states what the actual limit is. This is inspired by Raymond Hettinger’s [“Beyond PEP 8” talk](https://www.youtube.com/watch?v=wf-BqAjZb8M) and highway patrol not stopping you if you drive < 5mph too fast. Disable E501 to avoid duplicate warnings. Like E501, this error ignores long shebangs on the first line and urls or paths that are on their own line:`
