### ISSUE TITLE
Document no pip install on Windows

### ISSUE THREAD

**Issue by daikitag** [tskit-dev/msprime#2261]
I'm using Windows laptop, and I can install msprime on my computer by using `conda`, but I cannot install msprime by using `pip`, as the following message shows up:

`ERROR: Could not build wheels for msprime, which is required to install pyproject.toml-based projects`

Would it be possible for you to fix the issue, such that msprime can be pip installed on a windows laptop?

**Comment by jeromekelleher** [comment]
This isn't technically feasible because of our dependency on GSL, so pip install on Windows won't be supported for the foreseeable future. 

This is semi mentioned in the documentation, but it's in the wrong place and not obvious. https://tskit.dev/msprime/docs/latest/installation.html#term-Windows

We need to remove the current section under "pip install from source" and put in a ``warning`` block at the top of the ``via pip`` section to say that pip installations are not supported in Windows.
