### ISSUE TITLE
Statistical tests for DTWF with demography

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#441]
Should be able to extend the statistical tests done for the DTWF with and without recombination to include various demographic scenarios. 
- Growing/shrinking population
- Various different migration scenarios (island/stepping stone, etc)
- Simple demographic events (growth rate changes, etc).

**Comment by DomNelson** [comment]
This is taking a bit of detective work. It may be related to the scaling issue in #439 but it's not clear how. The simplest case showing departures is to have a mass migration which does nothing - either move 100% of the population to an empty population of the same size, or even a migration between two empty populations. In DTWF with pointless mass migration vs DTWF with no demographic events this gives something like:

num_trees:
![num_trees](https://user-images.githubusercontent.com/8810687/41998124-fce3de00-7a27-11e8-9c2f-9415ad6299a9.png)

tmrca_mean:
![tmrca_mean](https://user-images.githubusercontent.com/8810687/41998136-041f9e52-7a28-11e8-9c4c-5e76f30b3705.png)

The time of the mass migration seems to completely determine the size of the departures. A more recent mass migration changes this to 

num_trees:
![num_trees](https://user-images.githubusercontent.com/8810687/41998246-4d7c2cc8-7a28-11e8-9171-c6de115b6223.png)

tmrca_mean:
![tmrca_mean](https://user-images.githubusercontent.com/8810687/41998259-52d30124-7a28-11e8-9eb5-2611f4dc8aca.png)

Seems as though the most recent epoch isn't scaled properly, so the more time spent there the greater the departure. Still digging on this one.

**Comment by DomNelson** [comment]
All set. Just an issue with how demographic events were executed - happened at the wrong time, which then distorted the simulators internal time

num_trees:
![num_trees](https://user-images.githubusercontent.com/8810687/42110337-c0d9e282-7bae-11e8-976d-62289f9e1e7a.png)

tmrca_mean:
![tmrca_mean](https://user-images.githubusercontent.com/8810687/42110349-c8f6cbb0-7bae-11e8-8b18-c97b61eb020f.png)

I'm just finishing writing up some of these tests, then I'll figure out how to properly link my commits to these issues

**Comment by jeromekelleher** [comment]
Also excellent!

**Comment by DomNelson** [comment]
Ok I've streamlined the testing a bit, and for low-ish migration rates we've got good agreement

![num_trees](https://user-images.githubusercontent.com/8810687/44747266-bf11b000-aada-11e8-880c-adeb523f7440.png)
![tmrca_mean](https://user-images.githubusercontent.com/8810687/44747269-c20ca080-aada-11e8-93c7-0c11a4a7cd3f.png)

Higher though (noticeable above roughly 0.2-0.3) still showing some issues:

![num_trees](https://user-images.githubusercontent.com/8810687/44747381-0bf58680-aadb-11e8-86c8-31c150767977.png)
![tmrca_mean](https://user-images.githubusercontent.com/8810687/44747388-0ef07700-aadb-11e8-9019-10188f281c24.png)

Good news is that fairly flexible comparisons to SLiM are now possible, and those also look good for moderate migration. I checked the same scenario (2 pops, mig rates [0.5, 0.7] vs both Hudson and SLiM and the departures are very similar:

SLiM:
![num_trees](https://user-images.githubusercontent.com/8810687/44747575-80302a00-aadb-11e8-880f-584ac7371388.png)
![tmrca_mean](https://user-images.githubusercontent.com/8810687/44747577-80302a00-aadb-11e8-82f3-86b8267b9bce.png)

Hudson:
![num_trees](https://user-images.githubusercontent.com/8810687/44747686-c1c0d500-aadb-11e8-81e8-9c7663bcbffe.png)
![tmrca_mean](https://user-images.githubusercontent.com/8810687/44747688-c2f20200-aadb-11e8-9860-5ceede20f553.png)

I prioritized getting SLiM set up so that I wouldn't wonder if I was simulating a scenario where we might expect departures (these are pretty high migration rates) and I just didn't realize it.

Time to dig deeper into the migration!

**Comment by jeromekelleher** [comment]
Great stuff @DomNelson --- especially cool that we can do comparisons with SLiM now! Let me know if there's anything I can do to help.

**Comment by DomNelson** [comment]
Can close - PR #599

**Comment by jeromekelleher** [comment]
Closing.
