### ISSUE TITLE
Add ``from`` argument to simulate

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#503]
This is the "recapitation" feature to complete a partially specified history. Details to follow.

**Comment by bhaller** [comment]
I think this makes sense.  It will miss the SLiM 3 release and the initial SLiM 3 documentation, then, but that does not mean that it will miss the TreeSeq paper, since that will probably get finalized a little later.  So it can get rolled into a SLiM 3.0.1 or 3.1, and discussed in the manual at that point, and it can be in the TreeSeq paper; so if the schedule for 0.6.0 is tight, it makes sense to kick it down the road.  (The mutate() feature is more central, I think; I wouldn't want to release SLiM 3 without being able to talk about that in the manual, so that one is much more important to make it into 0.6.0.)  @petrelharp, do you agree?

**Comment by petrelharp** [comment]
I think postponing is wise, so we don't have too many things on our plate. We already have nontrivial work to do to set up the SLiM workflow where we initialize with a msprime-generated tree sequence, and deal with the results in python. (although, I guess recapitation would replace the need for this...)

**Comment by jeromekelleher** [comment]
OK, thanks. Moving this to the 0.6.1 milestone then.

**Comment by jeromekelleher** [comment]
Technically closed in #541, but see #572. Closing to move the discussion over there.
