### ISSUE TITLE
Is is it possible to do a SMC prime approximation? 

### ISSUE THREAD

**Issue by ismael2395** [tskit-dev/msprime#690]
Hi, 

Sorry if this is obvious from the documentation and I just missed it. I was just wondering if it was possible to simulate trees using your code that follow the SMC' model instead of the exact coalescent? 

Thanks!
Ismael

**Comment by jeromekelleher** [comment]
It's not documented yet, but it is possible to run smc/smc' simulations in msprime. You can do this using 

```python
ts = msprime.simulate(10, model="smc_prime")
```

You can also use ``model="smc"``. Don't expect any performance gains from this though, as the SMC models have been implemented with a naive rejection sampling algorithm.

The reason it hasn't been documented is because we have a bunch of other models in development and the interface might change (but I think it's pretty unlikely at this point).

**Comment by ismael2395** [comment]
Thanks @jeromekelleher !
