### ISSUE TITLE
machine readable demographic debugger

### ISSUE THREAD

**Issue by andrewkern** [tskit-dev/msprime#724]
is there a machine readable output version of the `.DemographyDebugger` function? I'm hoping to trace the population size history of population that has arbitrary demographic events

**Comment by jeromekelleher** [comment]
No, but we could certainly add one! Any ideas on what  the output should look like? See also #385.

**Comment by andrewkern** [comment]
I was thinking we could return a dictionary where the key:value pairs are population_name to 2D numpy arrays which contain times and popn sizes. If that sounds good I could work on this today-- where in the msprime code would be a natural place to put this?

**Comment by jeromekelleher** [comment]
Awesome. It might not even be necessary to that though, since you can get the information directly from the DemographyDebugger instance. It's not documented currently, but we could easily document it so it's a usable interface. The code is [here](https://github.com/tskit-dev/msprime/blob/master/msprime/simulations.py#L1216)

You probably want something like:
```python
dd = DemographyDebugger(...)
pop_size = np.array((num_pops, len(dd.epochs))
for j, epoch in enumerate(dd.epochs):
     for k, pop in enumerate(epoch.populations):
           pop_size[j, k] = pop.start_size
```

The information is all in there anyway, as I've decoupled the calculation and presentation code.

**Comment by jeromekelleher** [comment]
Is this still relevant @andrewkern, or are you happy with the recent API extensions?

**Comment by petrelharp** [comment]
@jgallowa07 is successfully pulling all the info we need out of this currently over at https://github.com/popgensims/stdpopsim/pull/63

**Comment by jeromekelleher** [comment]
I'm going to close this as we have the functionality now in a different form.
