### ISSUE TITLE
Statistical tests for Beta coalescent

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#859]
This issue is to track where we are at for statistical verification of the beta coalescent simulations.

Right now, it looks like we have some checks for the SFS when we have a very small sample size [here](https://github.com/tskit-dev/msprime/blob/master/verification.py#L1941)

What other checks can we do to verify the beta coalescent code? 

cc @eldonb and @JereKoskela

**Comment by jeromekelleher** [comment]
Can we test against HybridLambda here?

**Comment by JereKoskela** [comment]
My understanding is that HybridLambda is a haploid simulator, whereas the multiple merger coalescents we have implemented are diploid. It probably wouldn't take a great deal of work to remove diploidy from our code though: all we would have to do is not split up lineages participating in a merger into four groups as is done now.

One thing we can do is check correlations in coalescence times between two loci for samples of size 2 as a function of the various merger rates and the population-rescaled recombination rate. I have some ugly but explicit formulas for those (attached), which I think Joe even got around to implementing at some stage, though I'm not sure of that last part.

[two_locus_correlation.pdf](https://github.com/tskit-dev/msprime/files/4085400/two_locus_correlation.pdf)

**Comment by JereKoskela** [comment]
I addition to the correlation in coalescence times, we should replicate the expected site frequency spectrum in Figure 2 [here](https://www.sciencedirect.com/science/article/pii/S0040580916300053). Specifically, we should be looking at the X(a) = 1.5 case, because that falls squarely within the scope of the model that is already implemented.

Taken together, these two tests will validate that the merger rates are what we want them to be, and the recombination rate is what we want it to be.

**Comment by jeromekelleher** [comment]
Closed in #957 and #953
