### ISSUE TITLE
Generalise recombation map to "IntervalMap"

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#865]
With the msprime 1,0 code we can also have a "gene conversion" map where we vary the rate of GC events along the genome. Upstream, in stdpopsim we're also interested in associating various things with a genetic interval (although msprime's code may not end up being suitable as we might want things more general than just doubles as the keys).

@fbaumdicker, is a gene conversion rate map a sensible thing to do?

**Comment by fbaumdicker** [comment]
Absolutely! I have been talking about this with Richard Durbin in Aussois. He thinks this is an important feature we should include, and so do I. Richard suggested the way to go would be to start a gene conversion at the same rate a recombination event would occur, i.e. using the recombination map for the initial point of the gene conversion. Once the starting point is set, determine the track length from a geometrically distributed RV without taking the recombination map into account. Otherwise, a region with recombination rate zero could cause unusual long gene conversion tracks.

We should discuss this with the stdpopsim consortium, but it is almost impossible for me to attend the calls at Tuesday evenings.

**Comment by jeromekelleher** [comment]
Great, thanks. That'll be easy to do now.

There's the possibility of an entirely separate varying gene conversion rate (which would require another Fenwick tree). Is this a feature we should keep in mind for the future?

**Comment by fbaumdicker** [comment]
We will need an additional Fenwick tree anyway for the gene conversion events. The reason is that gene conversion events that start from the left of a segment and end within the segment need to be considered at the correct rate. This will require us to store more information about the conversion/recombination map to the left of the segment start.
That said, I also think a separate varying gene conversion rate/map might be useful in the future, so we should really keep this in mind.

**Comment by hyanwong** [comment]
Just to jump in, I think an interval map would be a useful thing in `tskit`, not just msprime. For instance, we want to be able to specify maps (e.g. for recombination) in tsinfer, which is nothing to do with running a simulation.

**Comment by jeromekelleher** [comment]
Done in #1138 but see #1172
