### ISSUE TITLE
samples from multiple populations

### ISSUE THREAD

**Issue by hyl317** [tskit-dev/msprime#868]
I am using msprime to simulate population splits and take samples from two populations at present. And I want to use tskit.write_vcf() to have separate vcf files for each of the two populations. Looking at the individual IDs of .vcf, I cannot tell which individuals come from which population. Are they in order of the population index? Maybe I just missed it in the API, but hope someone can clarify on that. Thanks a lot!

**Comment by petrelharp** [comment]
Hello! Good question. Since there's no individual data in an msprime simulation, outputting VCF simply takes all the "sample" nodes, pairs them up in order, and calls each pair an individual. So, samples `0` and `1` are the first individual (labeled `tsk_0` in the output); samples `2` and `3` are the second, etcetera.  (This is described [here](https://tskit.readthedocs.io/en/latest/python-api.html#tskit.TreeSequence.write_vcf), for future reference.) To check what population these are from, you have to check what population the samples are from. For instance, this will find out the population labels of each of the sample nodes:
```
[ts.node(s) for s in ts.samples()]
```
and this will find out the population for each of the individuals, as output by default to VCF:
```
assert(ts.num_samples % 2 == 0) # must be an even number of sampled genomes
for k in range(int(ts.num_samples / 2)):
  pop1 = ts.node(2 * k).population
  pop2 = ts.node(2 * k + 1).population
  assert(pop1 == pop2)
  print("individual tsk_{} is from population {}".format(k, pop1))
```

Hope that helps!

**Comment by jeromekelleher** [comment]
Yes, this isn't great at the moment unfortunately. We are hoping to improve this soon with support for individuals in msprime which will be used downstream in tskit to produce the VCF.

In the meantime, as well as what @petrelharp said, there's also the [TreeSequence.samples](https://tskit.readthedocs.io/en/latest/python-api.html#tskit.TreeSequence.samples) method which will return all the node IDs from a given population. So you could do something like

```python
for population in range(2):
    samples = ts.samples(population=population)
    pop_ts = ts.simplify(samples, filter_sites=False)   # Don't remove invariant '0' sites
    with open(f"population_{population}.vcf", "w") as f: 
        pop_ts.write_vcf(f, ploidy=2)
```

If solves your problem, can you close this issue please?

**Comment by hyl317** [comment]
yep, looks good! Thanks for the solution!
