### ISSUE TITLE
[C code] Unit test consistency of model time changes

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#889]
Add a unit test in C to check that all model time change functions are consistent, e.g.
```
    beta_generations_to_model_time(beta_model_time_to_generations(t)) == t,
    beta_model_time_to_generations(t) == beta_generation_rate_to_model_rate(t),
```

**Comment by grahamgower** [comment]
So I'm a little confused here. The tests mentioned above are trivially correct in all cases (by inspection of the code). But the following two sets of functions are not inverses (they are for the other models). Changing them to be inverses is fine---#890 says take the latter beta function as correct, I don't know about the dirac functions. And then the generations_to_time and time_to_generations functions will also need to be changed, in order to pass the tests mentioned above. So why does there exist both time coversion and rate conversion functions if they are intended to be identical?

dirac:
```
static double
dirac_generation_rate_to_model_rate(simulation_model_t *model, double rate)
{
    return rate * 4 * model->reference_size;
}

static double
dirac_model_rate_to_generation_rate(simulation_model_t *model, double rate)
{
    // This works for comparing dirac kingman case ... but why 4Ne^2
    return rate / ( 4 * gsl_pow_2(model->reference_size));
}
```

beta:
```
static double
beta_generation_rate_to_model_rate(simulation_model_t *model, double rate)
{
    return rate * 4 * model->reference_size;
}

static double
beta_model_rate_to_generation_rate(simulation_model_t *model, double rate)
{
    double alpha = model->params.beta_coalescent.alpha;
    double m = model->params.beta_coalescent.m;
    double phi = model->params.beta_coalescent.phi;
    double scalar = exp(log(alpha) - alpha * log(m)
            + gsl_sf_beta_inc (2 - alpha, alpha, phi)
            - (alpha - 1) * model->reference_size);
    return rate / ( 4 * scalar );
}
```

**Comment by jeromekelleher** [comment]
Honestly @grahamgower, I'm confused here too. @JereKoskela, any thoughts on this?

WRT to having functions to change both rate and time, it seemed better to have explicit functions to call in the API to try and make things less confusing, even if the actual implementations are identical. This time change stuff confuses the crap out of me, so I was trying to make it as simple and explicit as possible.

**Comment by grahamgower** [comment]
An equation for calculating phi would be great too.

beta_coalescent.phi is never set (a call to non-existent function `beta_compute_phi()` is commented out), so the rate scaling function just uses an uninitialised value right now (probably zero - I guess the memory is cleared somewhere).

**Comment by JereKoskela** [comment]
I showed up after the present plumbing was already in place, so can't really speak to the original rationale for why these are separate functions. I assumed it was some sort of readability consideration, but it is definitely true that they don't need to be. One is rescaling a time and the other of a rate, so they will be equal. That's true for both the Beta coalescent, the standard Hudson model, and probably any other conceivable coalescent as well.

Phi is a parameter in an unpublished model on which I'm not involved much, so I won't go into its details, largely because there's a good chance that I would get some of them wrong. However, what I can say for sure is that it is definitely a fixed parameter provided by the user (it shouldn't be calculated from anything), take values in (0, 1], and it should default to 1, whereupon the scalings should coincide with the Schweinsberg (2003) model. 

This project has been passed between people several times since its inception by now, so it isn't too surprising that there are loose ends around. Probing questions are very much appreciated in finding and fixing them, thanks @grahamgower!

**Comment by grahamgower** [comment]
That's very illuminating, thanks @JereKoskela. Is it possible that the currently unused `truncation_point` parameter is intended to be a human readable name for Phi?

**Comment by JereKoskela** [comment]
> That's very illuminating, thanks @JereKoskela. Is it possible that the currently unused `truncation_point` parameter is intended to be a human readable name for Phi?

Yes, I think that's very likely.

**Comment by grahamgower** [comment]
@jeromekelleher I'm pretty sure I can fix time/rate scaling for both the beta and dirac coalescent models now, with the info provided by @JereKoskela and @TPPSellinger.

**Comment by jeromekelleher** [comment]
> @jeromekelleher I'm pretty sure I can fix time/rate scaling for both the beta and dirac coalescent models now, with the info provided by @JereKoskela and @TPPSellinger.

Well, that would be outstanding @grahamgower, please go for it!

**Comment by jeromekelleher** [comment]
> I showed up after the present plumbing was already in place, so can't really speak to the original rationale for why these are separate functions. I assumed it was some sort of readability consideration, but it is definitely true that they don't need to be. One is rescaling a time and the other of a rate, so they will be equal. That's true for both the Beta coalescent, the standard Hudson model, and probably any other conceivable coalescent as well.

The rationale for having different functions was just for readability --- as I say, it's all very confusing anyway, so anything to make things a bit clearer seemed like a good idea. No reason we can't have one function just refer to the other in the implementation though.
